const float3 OGFX_CREEP_RADIANCE = vec3(10.0);

const float3 OGFX_CREEP_BASE_COLOR = vec3(0.35);
const float3 OGFX_CREEP_IRRADIANCE = (OGFX_CREEP_RADIANCE * OGFX_CREEP_BASE_COLOR) / (4.0 * MR_PI);
